name: Publish-Nuget-ReviewFile

# ワークフローが動作する条件を指定する
# 下記設定はmainブランチに対してワークフローのBuildが完了したことをトリガとする
# workflow_dispatchとはGitHub上でワークフローを手動実行できるトリガ。利便性が高いため基本設定するのを推奨
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

# 仮想環境で行わせる動作を記述する
jobs:
  publish-nuget:

    # 動作環境
    runs-on: ubuntu-latest

    # 環境変数
    env:
      # slnファイルの存在するフォルダの相対パス
      SolutionPath: src

    steps:

    # リポジトリの内容をチェックアウトする
    - name: Checkout
      uses: actions/checkout@v2

    # dotnet CLIを利用するためにdotNet環境を入れる
    # dotnet-versionにはSDKバージョンを指定する
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # 依存関係を復元する
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.SolutionPath}}

    # ビルドを実行する
    - name: Build
      run: dotnet build ${{env.SolutionPath}} --no-restore

    # ReviewFileを公開する
    # PROJECT_FILE_PATH:公開するプロジェクトのパス
    # VERSION_REGEX:公開する際のバージョン（下記は正規表現でcsproj内のPackageVersionタグを取得している）
    # TAG_FORMAT:gitのタグのフォーマット
    # NUGET_KEY:Nugetへの認証に必要なトークンを指定する
    - name: Publish to ReviewFile
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/ReviewFile/ReviewFile.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}