name: SonarCloud

# ワークフローが動作する条件を指定する
# 下記設定はmainブランチに対してsrcフォルダ以下を変更したプッシュあるいはプルリクエストをトリガとする
# workflow_dispatchとはGitHub上でワークフローを手動実行できるトリガ。利便性が高いため基本設定するのを推奨
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**']
  pull_request:
    branches: [main]
    paths: ['src/**']

# 仮想環境で行わせる動作を記述する
jobs:
  sonarcloud:

    # 動作環境
    runs-on: ubuntu-latest

    # 環境変数
    env:
      # slnファイルの存在するフォルダの相対パス
      SolutionPath: src

    steps:

    # リポジトリの内容をチェックアウトする
    # チェックアウトがエラーとなるため fetch-depth に 0 を指定し全タグ・全ブランチ・全履歴を取得するように設定する
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # dotnet CLIを利用するためにdotNet環境を入れる
    # dotnet-versionにはSDKバージョンを指定する
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    # SonarScannerの利用で必要のためjavaをいれる
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Set up Java 17, because SonarCloud requires it
        distribution: 'adopt'

    # SonarScannerをインストールする
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    # カバレッジレポート出力するためTestプロジェクトに対してcoverlet.msbuildをインストールする
    # dotnet add packageは1回のコマンドで複数プロジェクトへの動作をサポートしていないため、Testプロジェクトの数だけコマンドを追記する必要がある
    - name: Package Add coverlet.msbuild
      run: | 
        dotnet add src/ReviewFile.Tests/*.csproj package coverlet.msbuild
        dotnet add src/ReviewFileToJsonService.Tests/*.csproj package coverlet.msbuild

    # 依存関係を復元する
    - name: Restore dependencies
      run: dotnet restore 
      working-directory: ${{env.SolutionPath}}
    
    # 解析を開始する
    #   k:SonarCloudで設定したプロジェクトキー
    #   o:SonarCloudで設定した組織
    #   d:sonar.login:SonarCloudへの認証に必要なトークンを指定する（この引数を指定した場合は終了ステップにも追加する必要がある）
    #   d:sonar.host.url:SonarCloudのURL
    #   d:sonar.cs.opencover.reportsPaths:カバレッジレポートへのパスを指定する（SonarCloudに出力するカバレッジレポートを指定）
    - name: Begin Sonar analysis
      run: dotnet sonarscanner begin /k:"denso-create_LightningReview-ReviewFile" /o:"denso-create" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
    
    # 解析対象となるビルドとテストを実行する
    - name: Build
      run: dotnet build ${{env.SolutionPath}} --configuration Release --no-restore

    # テスト時にカバレッジレポートを出力するようにオプションを指定する
    #   /p:CollectCoverage=true:コードカバレッジを有効化し、カバレッジレポートを出力するようにする
    #   /p:CoverletOutputFormat=opencover:出力するカバレッジレポートの種類を指定
    - name: Test
      run: dotnet test ${{env.SolutionPath}} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    # 解析を終了する
    - name: End Sonar analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
