name: Build-SonarCloud

on:
  push:
    branches: [main]
    paths: ['src']
  pull_request:
    branches: [main]
    paths: ['src']

jobs:
  sonarcloud:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Restore
      run: dotnet restore src
    - name: Begin Sonar analysis
      run: dotnet sonarscanner begin /k:"denso-create/LightningReview-ReviewFile" /o:"denso-create" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: End Sonar analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}